Repository alielsokary/FoursquarePlaces, pull requests merged in 2021-12, with the labels that each got.

#1 Add a Codacy badge to README.md
  README.md
Labels: size/XS

#2 feat: Add Places Results Model
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/Models/PlacesResult.swift
Labels: size/M

#3 feat: Implement network layer
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/Scenes/Places/Service/VenuesService.swift
  FoursquarePlaces/Scenes/Places/View/ViewController.swift
  FoursquarePlaces/Services/Networking/Config.swift
  FoursquarePlaces/Services/Networking/FoursquareRouter.swift
  FoursquarePlaces/Services/Networking/HTTPMethod.swift
  FoursquarePlaces/Services/Networking/NetworkError.swift
  FoursquarePlaces/Services/Networking/NetworkService.swift
Labels: size/L

#4 feat: Add first design for Venues UI
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/Base.lproj/Main.storyboard
  FoursquarePlaces/Scenes/Places/View/Cell/VenueTableViewCell.swift
  FoursquarePlaces/Scenes/Places/View/Cell/VenueTableViewCell.xib
  FoursquarePlaces/Scenes/Places/View/VenuesViewController.swift
  FoursquarePlaces/Scenes/Places/View/ViewController.swift
Labels: size/L

#5 feat: Implement VenueListViewModel
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/Models/Venues.swift
  FoursquarePlaces/Scenes/Places/Service/VenuesService.swift
  FoursquarePlaces/Scenes/Places/View Model/VenueListViewModel.swift
  FoursquarePlaces/Scenes/Places/View Model/VenueViewModel.swift
  FoursquarePlaces/Scenes/Places/View/Cell/VenueTableViewCell.swift
  FoursquarePlaces/Scenes/Places/View/Cell/VenueTableViewCell.xib
  FoursquarePlaces/Scenes/Places/View/VenuesViewController.swift
  FoursquarePlaces/Services/Networking/Config.swift
  FoursquarePlaces/Services/Networking/FoursquareRouter.swift
Labels: size/L

#6 feat: Implement Storage Layer with core data
  .swiftlint.yml
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/FoursquarePlaces.xcdatamodeld/FoursquarePlaces.xcdatamodel/contents
  FoursquarePlaces/Models/Venues.swift
  FoursquarePlaces/Scenes/Places/View Model/VenueListViewModel.swift
  FoursquarePlaces/Scenes/Places/View Model/VenueViewModel.swift
  FoursquarePlaces/Services/Networking/NetworkError.swift
  FoursquarePlaces/Services/Networking/NetworkService.swift
  FoursquarePlaces/Services/Storage/StorageManager.swift
  FoursquarePlaces/Services/Storage/StorageService.swift
Labels: size/L

#7 feat: Update UI
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/Contents.json
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-1024.png
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-120.png
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-180.png
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-40.png
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-58.png
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-60.png
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-80.png
  FoursquarePlaces/Assets.xcassets/AppIcon.appiconset/icon-87.png
  FoursquarePlaces/Assets.xcassets/icon.imageset/Contents.json
  FoursquarePlaces/Assets.xcassets/icon.imageset/Group.png
  FoursquarePlaces/Base.lproj/LaunchScreen.storyboard
  FoursquarePlaces/Base.lproj/Main.storyboard
  FoursquarePlaces/Colors.xcassets/Contents.json
  FoursquarePlaces/Colors.xcassets/background.colorset/Contents.json
  FoursquarePlaces/Colors.xcassets/subtitles.colorset/Contents.json
  FoursquarePlaces/Colors.xcassets/titles.colorset/Contents.json
  FoursquarePlaces/Info.plist
  FoursquarePlaces/Library/Styling/FPLabel.swift
  FoursquarePlaces/Library/Styling/FontManager.swift
  FoursquarePlaces/Scenes/Places/View/Cell/VenueTableViewCell.swift
  FoursquarePlaces/Scenes/Places/View/Cell/VenueTableViewCell.xib
  FoursquarePlaces/Scenes/Places/View/VenuesViewController.swift
  FoursquarePlaces/Supporting files/Roboto-Bold.ttf
  FoursquarePlaces/Supporting files/Roboto-Medium.ttf
  FoursquarePlaces/Supporting files/Roboto-Regular.ttf
Labels: size/XL

#8 feat: Implement location manager
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/Scenes/Places/View Model/VenueListViewModel.swift
  FoursquarePlaces/Scenes/Places/View/VenuesViewController.swift
  FoursquarePlaces/Services/Location/LocationManager.swift
  FoursquarePlaces/Services/Networking/FoursquareRouter.swift
Labels: size/L

#9 feat: Add UISegmentedControl
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces/Base.lproj/Main.storyboard
  FoursquarePlaces/Scenes/About/View Model/AboutViewModel.swift
  FoursquarePlaces/Scenes/About/View/AboutViewController.swift
  FoursquarePlaces/Scenes/Home/HomeViewController.swift
  FoursquarePlaces/Scenes/Venues/Service/VenuesService.swift
  FoursquarePlaces/Scenes/Venues/View Model/VenueListViewModel.swift
  FoursquarePlaces/Scenes/Venues/View Model/VenueViewModel.swift
  FoursquarePlaces/Scenes/Venues/View/Cell/VenueTableViewCell.swift
  FoursquarePlaces/Scenes/Venues/View/Cell/VenueTableViewCell.xib
  FoursquarePlaces/Scenes/Venues/View/VenuesViewController.swift
Labels: size/L

#10 feature: Add unit tests
  FoursquarePlaces.xcodeproj/project.pbxproj
  FoursquarePlaces.xcodeproj/xcshareddata/xcschemes/FoursquarePlaces.xcscheme
  FoursquarePlaces/App/SceneDelegate.swift
  FoursquarePlaces/Base.lproj/Main.storyboard
  FoursquarePlaces/Info.plist
  FoursquarePlaces/Models/Venues.swift
  FoursquarePlaces/Scenes/Venues/View Model/VenueListViewModel.swift
  FoursquarePlaces/Scenes/Venues/View Model/VenueViewModel.swift
  FoursquarePlacesTests/FoursquarePlacesTests.swift
  FoursquarePlacesTests/NetworkServiceMock.swift
  FoursquarePlacesTests/StorageServiceMock.swift
  FoursquarePlacesTests/VenueListViewModelTests.swift
  FoursquarePlacesTests/VenueViewModelTests.swift
Labels: size/L
